# Generated by Django 3.2.7 on 2021-09-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycalendar', '0003_auto_20210926_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='hex_color',
            field=models.CharField(default='FFFFFF', max_length=6),
            preserve_default=False,
        ),
    ]
